import type { Metadata } from "next";

import "./globals.css";
import { Bounce, ToastContainer } from "react-toastify";
import NavBar from "./components/navbar/navBar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="fr">
			<body>
				<ToastContainer
					position="top-center"
					autoClose={6000}
					hideProgressBar={true}
					newestOnTop={false}
					closeOnClick={false}
					rtl={false}
					pauseOnFocusLoss
					draggable
					pauseOnHover
					theme="light"
					transition={Bounce}
				/>
				{children}
			</body>
		</html>
	);
}
