import type { Metadata } from "next";

import "./globals.css";
import { Bounce, ToastContainer } from "react-toastify";

import { SessionProvider } from "next-auth/react";

import { auth } from "../../auth";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await auth();
	return (
		<html lang="fr">
			<body>
				<ToastContainer
					position="top-center"
					autoClose={6000}
					hideProgressBar={true}
					newestOnTop={false}
					closeOnClick={false}
					rtl={false}
					pauseOnFocusLoss
					draggable
					pauseOnHover
					theme="light"
					transition={Bounce}
				/>
				<SessionProvider session={session}>{children}</SessionProvider>
			</body>
		</html>
	);
}
